"""create prompt table

Revision ID: 778fb3c20409
Revises: d571c701abcf
Create Date: 2025-07-31 13:26:58.485892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778fb3c20409'
down_revision = 'd571c701abcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=225), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('forked_from', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['forked_from'], ['prompt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt')
    # ### end Alembic commands ###
